CREATE DATABASE library;
use books;
CREATE TABLE books (`id` BIGINT NOT NULL AUTO_INCREMENT, `title` VARCHAR(2048) NOT NULL, `author` VARCHAR(2048) NOT NULL, `image_pathLocation` VARCHAR(1024) NOT NULL, PRIMARY KEY(`id`));
INSERT INTO books (title, author, image_pathLocation) Values ('Exploring War and Weapons', 'Brian Williams', 'https://sourcebucket-aleppo-library-resized.s3.eu-west-2.amazonaws.com/resized-Exploring+War+And+Weapons.jpg'

CREATE TABLE quotes ( author varchar(255), title varchar(255) );
Insert Into quotes (title, author) Values ('Engineering Electromagnetics', 'William H. Hayt,Jr');
Insert Into quotes (title, author) Values ('Unix Power Tools', 'Shelly Powers, Jerry Peek, Tim O Reilly, Mike Loukides');
Insert Into quotes (title, author) Values ('Digital Communications Fundamentals and Applications', 'Bernard Sklar');
Insert Into quotes (title, author) Values ('Microwave Engineering', 'David M. Pozar');
Insert Into quotes (title, author) Values ('Business Data Communications and Networking', 'Jerry FitzGerald, Alan Dennis');
Insert Into quotes (title, author) Values ('Antenna Theory Analysis And Design', 'Constantine A. Ballanis');
Insert Into quotes (title, author) Values ('Mathematics for Electrical Engineering and Computing', 'Mary Attenborough');
Insert Into quotes (title, author) Values ('A History of the Arab Peoples', 'Albert Hourani with an afterword by Malise Ruthven');
Insert Into quotes (title, author) Values ('Fear', 'Ranulph Fiennes');
Insert Into quotes (title, author) Values ('Exploring War and Weapons', '');
Insert Into quotes (title, author) Values ('Exploring The Age of Dinosaurs', '');
Insert Into quotes (title, author) Values ('Exploring The Age of Steam', '');
Insert Into quotes (title, author) Values ('Exploring The Planets', '');
Insert Into quotes (title, author) Values ('Exploring Knights And Castles', '');
Insert Into quotes (title, author) Values ('The Midnight World', '');
Insert Into quotes (title, author) Values ('Exploring Animal Journeys', '');
Insert Into quotes (title, author) Values ('Exploring Under The Sea', '');
Insert Into quotes (title, author) Values ('Exploring Animal Homes', '');
Insert Into quotes (title, author) Values ('Exploring The World Of Speed', '');
Insert Into quotes (title, author) Values ('Exploring The World Of Robots', '');
Insert Into quotes (title, author) Values ('Delhi Agra & Jaipur', 'Eyewitness Travel');
Insert Into quotes (title, author) Values ('Istanbul', 'Eyewitness Travel');
Insert Into quotes (title, author) Values ('Malaysia & Singapore', 'Eyewitness Travel');
Insert Into quotes (title, author) Values ('Australia New Zeland The Essential Guide 2011-2012', 'Austravel');
Insert Into quotes (title, author) Values ('Have I Got News For You Guide To Modern Britain', 'Nick Mrtin');
Insert Into quotes (title, author) Values ('Mister Pip', 'Lloyd Jones');
Insert Into quotes (title, author) Values ('The Casual Vacancy', 'J.K.Rowling');
Insert Into quotes (title, author) Values ('Physics The Easy Way', 'Robert L. Lehrman');
Insert Into quotes (title, author) Values ('Advanced Mathematics Core 3 & 4', 'Hugh Neill and Douglas Quadling');
Insert Into quotes (title, author) Values ('Physics Demystified', 'Stan Gibilisco');
Insert Into quotes (title, author) Values ('Advanced Mathematics Core 1 & 2', 'Hugh Neill and Douglas Quadling');
Insert Into quotes (title, author) Values ('Engineering Mechanics Dynamics In SI Units', 'Peter Schiavone and R.C. Hibbeler');
Insert Into quotes (title, author) Values ('Schaum''s ouTlines Calculus', 'Frank Ayres Jr. and Elliott Mendelson');
Insert Into quotes (title, author) Values ('IGCSE Physics for Edexcel', 'Malcom Bradley and Chris Sunley');
Insert Into quotes (title, author) Values ('IGCSE Mathematics for Edexcel', 'Paul Metcalf');
Insert Into quotes (title, author) Values ('The complete Mathematics Study Guide for AS and A2 Success', 'Peter Sherran and Janet Crawshaw');
Insert Into quotes (title, author) Values ('The President Is Missing', 'Bill Clinton And James Pattersons');
Insert Into quotes (title, author) Values ('Churchill The Life An Authorised Pictorial Biography', 'Max Arthur');
Insert Into quotes (title, author) Values ('Assignment: Jurusalem, Target: Antichrist Assasins', 'Tim Lahaye and Jerry B.Jenkins');
Insert Into quotes (title, author) Values ('A Promised Land', 'Barack Obama');
Insert Into quotes (title, author) Values ('4 Blood Types, 4 Diets Eat Right For Your Type The Individualized Diet Solution to Staying Health, Living Longer & Achieving Your Ideal Weight', 'Dr Peter J.D Adamo with Catherine Whitney');
Insert Into quotes (title, author) Values ('Born Survivors', 'Wendy Holden');
Insert Into quotes (title, author) Values ('The Churchill Factor', 'Boris Johnson');
Insert Into quotes (title, author) Values ('The Room Where It Happened A White House Memoir', 'John Bolton');
Insert Into quotes (title, author) Values ('The Biggest Secret', 'David Icke');