#cloud-config
# Add groups to the system
# Adds the ubuntu group with members 'root' and 'sys'
# and the empty group hashicorp.
groups:
  - amazon: [root,sys]
  - cloud-user

# Add users to the system. Users are added after groups are added.
users:
  - default
  - name: salt
    gecos: salt
    shell: /bin/bash
    primary_group: cloud-user
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    lock_passwd: false
    ssh_authorized_keys:
      - -----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAgQnS/GCWmS8yik3FmeUr
O4xIFKr5PsdhJghi+gVotVo9sQWsiATilZ+nFEZ3R4yWlqSndM/ZVVfEn/qyAxEs
xQ7pWYlemxGm2508RWTDTl6tR/EWifXA5Ei+W6Pna8mjFGVXKQWG0uCwSkDOpZWH
xEdCLvX7BxDwV6oihv39plDD1qz9O9ELdNhDw6bXSWqFzcmrtOzXWfVWuf7h6esD
LahT9W4JVDMasnVOJmMSZAjZc4VzCwFpwS1/m6B5rmx6Gl3YbdZ7hRaLZIiZkDZ7
w7XNifViPmLidu97adGAgLzF8qSXYYhwVv322rzBAoBNE7I8c4gVVrRhqYSSJS68
TQIDAQAB
-----END PUBLIC KEY-----

# salt-master

runcmd:
  - sudo su salt
  - sudo mkdir /srv/salt
  - sudo mkdir /srv/salt/nginx
  - sudo mkdir /srv/pillar
  - sudo rpm --import https://repo.saltproject.io/salt/py3/amazon/2/x86_64/SALT-PROJECT-GPG-PUBKEY-2023.pub
  - curl -fsSL https://repo.saltproject.io/salt/py3/amazon/2/x86_64/latest.repo | sudo tee /etc/yum.repos.d/salt-amzn.repo
  - sudo yum install salt-master -y
  - sudo yum install salt-ssh -y
  - sudo systemctl enable salt-master && sudo systemctl start salt-master
  - sudo systemctl restart salt-master.service
  - sudo aws s3 cp s3://directions-from-court/master /etc/salt
  - sudo systemctl restart salt-master.service